language: go

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

go:
- "1.10"

before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.3.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.3.deb
  - sudo service elasticsearch start
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo service postgresql restart 10
  - sleep 10

before_script:
  - psql -U postgres -c "CREATE DATABASE elastic_test;"

script:
- go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/rp-indexer/...

after_success:
- bash <(curl -s https://codecov.io/bash)
- rm coverage.text
- rm elasticsearch-6.2.3.deb
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

